// <auto-generated />
using Asssignment1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Asssignment1.Migrations
{
    [DbContext(typeof(ReciepesAllContext))]
    partial class ReciepesAllContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Asssignment1.Models.ReciepeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("reciepeIngredients")
                        .IsRequired();

                    b.Property<string>("reciepeName")
                        .IsRequired();

                    b.Property<string>("reciepeProcedure")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ReciepeModel");
                });
#pragma warning restore 612, 618
        }
    }
}
